name: Build and deploy the web app to Azure Web App

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: projectempire    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up emsdk
        uses: mymindstorm/setup-emsdk@v11
        
      - name: Run python script
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: |
          cd client
          python populate.py
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: "client/game-client/package-lock.json"
          
      - name: npm install, build, and test
        run: |
          cd client
          cd game-client
          npm install
          npm run build --if-present
          # Should add code testing
          
      - name: Copy the React app to out dir of express server
        run: |
          cd server
          cd outDir
          mkdir client
          sudo cp -a ../../client/game-client/dist/. ./client/
        
      - name: Build the express server
        run: |
         cd server
         npm i
         npm run build
         
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: server/outDir
         
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp 
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
